In [16]:
import pandas as pd

In [17]:
df = pd.read_json("myfile.json")

df.describe()

       CustomerID
count   24.000000
mean     2.000000
std      0.834058
min      1.000000
25%      1.000000
50%      2.000000
75%      3.000000
max      3.000000

In [18]:
df.head(10)

   CustomerID     Name                Email
0           1    Alice    alice@example.com
1           2      Bob      bob@example.com
2           3  Charlie  charlie@example.com
3           1    Alice    alice@example.com
4           2      Bob      bob@example.com
5           3  Charlie  charlie@example.com
6           1    Alice    alice@example.com
7           2      Bob      bob@example.com
8           3  Charlie  charlie@example.com
9           1    Alice    alice@example.com

In [19]:
df = df.fillna(0)

In [20]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\program files\python\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\program files\python\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
df1 = pd.read_xml("emp.xml")
df1

      id            Name           Description  Status
0  OP001    StartService    Starts the service  Active
1  OP002     StopService     Stops the service  Active
2  OP003  RestartService  Restarts the service  Active

In [22]:
import pandas as pd
df2 = pd.read_parquet("sample-users.parquet")
df2.describe()

           user_id          age      balance                 signup_date
count  1000.000000  1000.000000  1000.000000                        1000
mean    500.500000    46.672000  5082.639590  2022-10-23 10:45:07.200000
min       1.000000    18.000000    34.730000         2020-01-01 00:00:00
25%     250.750000    32.000000  2742.807500         2021-06-03 06:00:00
50%     500.500000    47.000000  5097.490000         2022-12-07 00:00:00
75%     750.250000    61.000000  7534.075000         2024-02-14 12:00:00
max    1000.000000    75.000000  9995.950000         2025-06-22 00:00:00
std     288.819436    16.946374  2859.475186                         NaN

In [23]:
!pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in c:\users\o734708\appdata\roaming\python\python314\site-packages (25.0.1)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import pandas as pd
df2 = pd.read_parquet("sample-users.parquet")
df2.describe()

           user_id          age      balance                 signup_date
count  1000.000000  1000.000000  1000.000000                        1000
mean    500.500000    46.672000  5082.639590  2022-10-23 10:45:07.200000
min       1.000000    18.000000    34.730000         2020-01-01 00:00:00
25%     250.750000    32.000000  2742.807500         2021-06-03 06:00:00
50%     500.500000    47.000000  5097.490000         2022-12-07 00:00:00
75%     750.250000    61.000000  7534.075000         2024-02-14 12:00:00
max    1000.000000    75.000000  9995.950000         2025-06-22 00:00:00
std     288.819436    16.946374  2859.475186                         NaN

In [25]:
df4 = pd.read_orc("orc_test1_sample.orc")
df4

,boolean1,byte1,short1,int1,long1,float1,double1,bytes1,string1,middle,list,map
0,False,1,1024,65536,9223372036854775807,1.0,-15.0,b'\x00\x01\x02\x03\x04',hi,"{'list': [{'int1': 1, 'string1': 'bye'}, {'int...","[{'int1': 3, 'string1': 'good'}, {'int1': 4, '...",[]
1,True,100,2048,65536,9223372036854775807,2.0,-5.0,b'',bye,"{'list': [{'int1': 1, 'string1': 'bye'}, {'int...","[{'int1': 100000000, 'string1': 'cat'}, {'int1...","[(chani, {'int1': 5, 'string1': 'chani'}), (ma..."

In [26]:
df6 = pd.read_html("index.html")
df6

[    Employee ID Employee Name Department Designation  Salary
 0          1001    Employee 1         IT    Engineer   51000
 1          1002    Employee 2         HR     Analyst   52000
 2          1003    Employee 3    Finance     Manager   53000
 3          1004    Employee 4      Sales        Lead   54000
 4          1005    Employee 5  Marketing   Executive   55000
 ..          ...           ...        ...         ...     ...
 95         1096   Employee 96         IT    Engineer  146000
 96         1097   Employee 97         HR     Analyst  147000
 97         1098   Employee 98    Finance     Manager  148000
 98         1099   Employee 99      Sales        Lead  149000
 99         1100  Employee 100  Marketing   Executive  150000

 [100 rows x 5 columns]]

In [27]:
df7 = pd.read_json("Product.json")
df7["value"]

0     {'ID': 0, 'Name': 'Bread', 'Description': 'Who...
1     {'ID': 1, 'Name': 'Milk', 'Description': 'Low ...
2     {'ID': 2, 'Name': 'Vint soda', 'Description': ...
3     {'ID': 3, 'Name': 'Havina Cola', 'Description'...
4     {'ID': 4, 'Name': 'Fruit Punch', 'Description'...
5     {'ID': 5, 'Name': 'Cranberry Juice', 'Descript...
6     {'ID': 6, 'Name': 'Pink Lemonade', 'Descriptio...
7     {'ID': 7, 'Name': 'DVD Player', 'Description':...
8     {'ID': 8, 'Name': 'LCD HDTV', 'Description': '...
9     {'@odata.type': '#ODataDemo.FeaturedProduct', ...
10    {'@odata.type': '#ODataDemo.FeaturedProduct', ...
Name: value, dtype: object

In [28]:
import pandas as pd
df9 = pd.read_excel("emp_Xl.xlsx",engine="openpyxl")
df9

FileNotFoundError: [Errno 2] No such file or directory: 'emp_Xl.xlsx'

In [ ]:
!pip install openpyxl xlrd pyarrow lxml html5lib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\program files\python\lib\site-packages (3.1.5)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: pyarrow in c:\users\o734708\appdata\roaming\python\python314\site-packages (25.0.1)
Requirement already satisfied: lxml in c:\program files\python\lib\site-packages (6.1.1)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: et-xmlfile in c:\program files\python\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.9 in c:\program files\python\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, xlrd, html5lib

   ------------- -------------------------- 1/3 [xlrd]
   -------------------------- ------------- 2/3 [html5lib]
   -------------------------- ------------- 2/3 [html5lib]
   ---------------------------------------- 3/3 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.5.1 xlrd-2.0.2

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
df9 = pd.read_csv("emp_2.xls")
df9.to_excel("emp_21.xlsx", index=False, engine="openpyxl")
df9.describe()

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000

In [ ]:
import pandas as pd
df10 = pd.read_excel("emp_21.xlsx")
df10.shape
sort_sal = df10["Salary"].sort_values() #It returning the Series
sort_sal2 = df10.sort_values("Salary") #It return the Data FrameS
# print(sort_sal2.head(20))

summ = df10["Salary"].sum()
print(summ)
count1 = df10["Gender"].isna().sum()
print(count1)
df10["Gender"].fillna("No Gender", inplace=True)
count2 = df10["Gender"].isna().sum()
print(count2)

90662181
145
145

C:\Users\O734708\AppData\Local\Temp\ipykernel_24568\268551231.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df10["Gender"].fillna("No Gender", inplace=True)

In [ ]:
import numpy as np
print(df10.isna().sum())
df10["Senior Management"]= df10["Senior Management"].replace(to_replace=np.nan, value=True)
print(df10.isna().sum())

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management      0
Team                  43
dtype: int64
First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management      0
Team                  43
dtype: int64

In [ ]:
import pandas as pd
s1 = pd.read_csv("products-1000.csv")
s1.columns
# s1.groupby("Availability").count()
s1["Category"].skew
s1["Category"].kurtosis
s1["Price"].value_counts
print(round(s1["Stock"].kurtosis(),4))
print(round(s1["EAN"].kurtosis(),3))
print(round(s1["Price"].mean(),3))
print(round(s1["Price"].median(),3))
print("Min - ",min(s1["Category"]))
print("Max - ",max(s1["Category"]))
print("Max - ",(s1["Category"].mode()))
ss = s1.groupby("Category").agg({"Price":"mean" , "Stock":"sum"})
ss

-1.2153
-1.197
506.549
497.5
Min -  Accessories (Bags, Hats, Belts)
Max -  Women's Clothing
Max -  0    Books & Stationery
Name: Category, dtype: str

                                      Price  Stock
Category
Accessories (Bags, Hats, Belts)  503.206897  12007
Automotive                       448.242424  15689
Beauty & Personal Care           607.034483  15634
Bedding & Bath                   484.000000   7982
Books & Stationery               508.743590  19858
Cameras & Accessories            539.875000  13307
Camping & Hiking                 429.241379  18195
Cleaning Supplies                471.085714  17340
Clothing & Apparel               478.250000  17945
Cycling                          453.800000  16463
Fishing & Hunting                492.437500  15067
Fitness Equipment                615.842105   6873
Fragrances                       403.343750  15759
Furniture                        468.038462  14824
Grooming Tools                   549.605263  16272
Haircare                         528.640000  14489
Headphones & Earbuds             461.906250  15973
Health & Wellness                575.394737  17780
Home & Kitchen                   572.575758  19524
Home Decor                       511.805556  17454
Kids' Clothing                   585.590909  11086
Kitchen Appliances               470.666667  16326
Laptops & Computers              448.240000  13147
Makeup                           514.037037  12583
Men's Clothing                   462.678571   9216
Office Supplies                  412.076923  12264
Shoes & Footwear                 603.206897  15388
Skincare                         490.200000  17205
Smartphones                      589.192308  13355
Smartwatches                     502.750000  20164
Sports & Outdoors                498.142857  13874
Team Sports                      546.259259  14317
Toys & Games                     521.375000  11476
Women's Clothing                 538.434783  12946

In [ ]:
import pandas as pd
s2 = pd.read_csv("my_file1.csv")
s2 = s2.fillna(0)
s2["Actual gross"] = s2["Actual gross"].str.replace(',', '', regex=False).str.replace('$' , "" ,regex=False)
s2["Actual gross"] = s2["Actual gross"].str.replace('[e]', '', regex=False)
s2["Actual gross"] = s2["Actual gross"].str.replace('[b]', '', regex=False)
s2["Actual gross(in 2022 dollars)"] = s2["Actual gross(in 2022 dollars)"].str.replace(',', '', regex=False).str.replace('$' , "" ,regex=False)
s2["Average gross"] = s2["Average gross"].str.replace(',', '', regex=False).str.replace('$' , "" ,regex=False)
s2["Peak"] = s2["Peak"].str.replace(r"\[\d+\]","", regex=True)
s2["All Time Peak"] = s2["All Time Peak"].str.replace(r"\[\d+\]","", regex=True)
s2

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival †,2023–2024,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,[15][16]
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour *,2009–2011,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,615385,[20]
14,15,2[c],NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186,[26]

In [ ]:
s2["Peak"] = s2["Peak"].str.extract(r'(\d+)')

s2.head(20)

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival †,2023–2024,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,[15][16]
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour *,2009–2011,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186,[26]

In [ ]:
s2['Tour title'] = (

s2['Tour title']

.str.replace(r'\[.*?\]', '', regex=True) # remove [4], [a], [10]

.str.replace('†', '', regex=False) # remove dagger symbol

.str.replace('‡', '', regex=False) # remove double dagger

.str.strip() # remove extra spaces

)
s2

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival,2023–2024,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,[15][16]
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour *,2009–2011,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour,2002–2005,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186,[26]

In [ ]:
s2["Artist"] = s2["Artist"].str.replace("" , "" , regex=False)
s2

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008–2009,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival,2023–2024,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,[15][16]
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour *,2009–2011,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014–2015,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour,2002–2005,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013–2014,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012–2013,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015–2016,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013–2014,86,1744186,[26]

In [ ]:
s2["Year(s)"] = s2["Year(s)"].str.extract(r'(\d{4})')
s2

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008,131,2137405,[11]
7,7,NaN,NaN,257600000,257600000,Pink,Summer Carnival,2023,41,6282927,[12]
8,9,NaN,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,NaN,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,NaN,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013,132,1735606,[15][16]
11,12,NaN,14,227400000,295301479,Lady Gaga,The Monster Ball Tour *,2009,203,1118227,[18]
12,13,NaN,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour,2002,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,NaN,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013,142,1295775,[22]
16,17,NaN,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012,98,1734694,[d]
17,18,NaN,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015,82,2070732,[4]
18,19,NaN,NaN,167700000,204486106,Adele,Adele Live 2016,2016,121,1385950,[25]
19,20,NaN,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013,86,1744186,[26]

In [ ]:
s2["Peak"] = s2["Peak"].str.extract(r'(\d+)')
s2["Peak"] = s2["Peak"].fillna(0 , inplace=True)
s2

C:\Users\O734708\AppData\Local\Temp\ipykernel_24252\347663822.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  s2["Peak"] = s2["Peak"].fillna(0 , inplace=True)

,Rank,Peak,All Time Peak,Actual gross,Actual gross(in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018,156,2546795,[7]
4,5,2,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]
5,6,2,10,305158363,388978496,Madonna,The MDNA Tour,2012,88,3467709,[9]
6,7,2,NaN,280000000,381932682,Celine Dion,Taking Chances World Tour,2008,131,2137405,[11]
7,7,0,NaN,257600000,257600000,Pink,Summer Carnival,2023,41,6282927,[12]
8,9,0,NaN,256084556,312258401,Beyoncé,The Formation World Tour,2016,49,5226215,[13]
9,10,0,NaN,250400000,309141878,Taylor Swift,The 1989 World Tour,2015,85,2945882,[14]
10,11,0,NaN,229100000,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013,132,1735606,[15][16]
11,12,0,14,227400000,295301479,Lady Gaga,The Monster Ball Tour *,2009,203,1118227,[18]
12,13,0,NaN,204000000,251856802,Katy Perry,Prismatic World Tour,2014,151,1350993,[19]
13,14,1,NaN,200000000,299676265,Cher,Living Proof: The Farewell Tour,2002,325,615385,[20]
14,15,2,NaN,194000000,281617035,Madonna,Confessions Tour,2006,60,3233333,[5]
15,16,0,NaN,184000000,227452347,Pink,The Truth About Love Tour,2013,142,1295775,[22]
16,17,0,NaN,170000000,213568571,Lady Gaga,Born This Way Ball,2012,98,1734694,[d]
17,18,0,NaN,169800000,207046755,Madonna,Rebel Heart Tour,2015,82,2070732,[4]
18,19,0,NaN,167700000,204486106,Adele,Adele Live 2016,2016,121,1385950,[25]
19,20,0,NaN,150000000,185423109,Taylor Swift,The Red Tour,2013,86,1744186,[26]

In [ ]:
s2["Actual gross(in 2022 dollars)"] = (
    s2["Actual gross(in 2022 dollars)"].fillna(0 , inplace=True)
)
s2["Actual gross"].dtype

C:\Users\O734708\AppData\Local\Temp\ipykernel_24252\1252757123.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  s2["Actual gross(in 2022 dollars)"].fillna(0 , inplace=True)

In [ ]:
s2["Actual gross"] = pd.to_numeric(
    s2["Actual gross"]
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)

In [ ]:
s2["Average gross"] = pd.to_numeric(
    s2["Average gross"]
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True),
    errors='coerce'
)

In [ ]:
s2["Actual gross"].dtype

dtype('int64')

In [ ]:
s2["Actual gross"].dtype

dtype('int64')

In [ ]:
col = s2["Actual gross"]

print("Mean      :", col.mean())
print("Median    :", col.median())
print("Mode      :")
print(col.mode())

print("Minimum   :", col.min())
print("Maximum   :", col.max())


print("Variance  :", col.var())
print("Std Dev   :", col.std())

print("Skewness  :", col.skew())
print("Kutosis   :", col.kurtosis())

Mean      : 287950903.25
Median    : 239750000.0
Mode      :
0     150000000
1     167700000
2     169800000
3     170000000
4     184000000
5     194000000
6     200000000
7     204000000
8     227400000
9     229100000
10    250400000
11    256084556
12    257600000
13    280000000
14    305158363
15    345675146
16    397300000
17    411000000
18    579800000
19    780000000
Name: Actual gross, dtype: int64
Minimum   : 150000000
Maximum   : 780000000
Variance  : 2.443857522330847e+16
Std Dev   : 156328421.03503916
Skewness  : 2.0808195845462922
Kutosis   : 4.631257681345044

In [29]:
s2.to_csv("Clean_Csv_File.csv" , index=False)

NameError: name 's2' is not defined

In [30]:
col = s2["Average gross"]

print("Quantile 1 : ", col.quantile(0.25))
print("Quantile 2 : ", col.quantile(0.75))

print("Mean      :", col.mean())
print("Median    :", col.median())
print("Mode      :")
print(col.mode())

print("Minimum   :", col.min())
print("Maximum   :", col.max())


print("Variance  :", col.var())
print("Std Dev   :", col.std())

print("Skewness  :", col.skew())
print("Kutosis   :", col.kurtosis())

NameError: name 's2' is not defined

In [ ]:
col = s2["Average gross"]

print("Quantile 1 : ", col.quantile(0.25))
print("Quantile 2 : ", col.quantile(0.75))

NameError: name 's2' is not defined

In [31]:
import pandas as pd

In [37]:
df = pd.read_csv("Clean_Csv_File.csv")
dff = df["Average gross"]
df3 = pd.read_csv("products-1000.csv")
df2 = df3["Price"]
print("Quantile 1 : ", dff.quantile(0.25))
print("Quantile 2 : ", dff.quantile(0.75))
# dff.dtype


print("Quantile Price : ", df2.quantile(0.25))
print("Quantile Price : ", df2.quantile(0.75))
df2.dtype

Quantile 1 :  1647508.0
Quantile 2 :  4933024.25
Quantile Price :  284.75
Quantile Price :  757.25

dtype('int64')