In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("healthcare_dataset.csv")

In [4]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['Age'] < lower_bound) | (df['Age'] > upper_bound)]
print(f"Lower Threshold Boundary: {lower_bound}")
print(f"Upper Threshold Boundary: {upper_bound}")
print("\nDetected Outliers in 'age' column:")
print(outliers)

Lower Threshold Boundary: -14.5
Upper Threshold Boundary: 117.5

Detected Outliers in 'age' column:
Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

In [44]:
Q1 = df['Billing Amount'].quantile(0.25)
Q3 = df['Billing Amount'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 0.5 * IQR
upper_bound = Q3 + 0.5 * IQR
outliers = df[(df['Billing Amount'] < lower_bound) | (df['Billing Amount'] > upper_bound)]
print(f"Lower Threshold Boundary: {lower_bound}")
print(f"Upper Threshold Boundary: {upper_bound}")
print("\nDetected Outliers in 'Billing Amount' column:")
print(len(outliers))

Lower Threshold Boundary: 52764.277
Upper Threshold Boundary: 52764.277

Detected Outliers in 'Billing Amount' column:
0

In [ ]:
import pandas as pd


mean_billing = df['Billing Amount'].mean()
std_billing = df['Billing Amount'].std()
df['Z_Score'] = (df['Billing Amount'] - mean_billing) / std_billing
outliers = df[df['Z_Score'].abs() > 1.9]
print(f"Dataset Mean: {mean_billing}")
print(f"Dataset Standard Deviation: {std_billing}\n")
print(f"Found {len(outliers)} outliers using the Z-score method:")
print(outliers[['Name', 'Age', 'Billing Amount', 'Z_Score']])

Dataset Mean: 25539.316097211777
Dataset Standard Deviation: 14211.45443086404

Found 4 outliers using the Z-score method:
                Name  Age  Billing Amount   Z_Score
36349  tOdd CARrILlO   51    52764.276736  1.915705
42621      joHn hahN   80    -1520.420555 -1.904079
47589     james lUnA   64    -2008.492140 -1.938423
48659    EMMA savAGE   57    -1660.009373 -1.913902

In [34]:
import pandas as pd
df1 = pd.read_csv("Clean_Health.csv")
doctor_counts = df1.groupby('Doctor')['Name'].count().reset_index()
doctor_counts

                            Doctor  Name
0      Aaron Acevedo                   1
1      Aaron Adams                     1
2      Aaron Aguilar                   1
3      Aaron Alexander                 1
4      Aaron Anderson                  1
...                            ...   ...
39934  Zoe Knight                      1
39935  Zoe Nichols                     1
39936  Zoe Roberts                     1
39937  Zoe Shea                        2
39938  Zoe Wallace                     1

[39939 rows x 2 columns]

In [35]:
doctor_counts.columns = ['Doctor Name', 'Total_Patients_Treated']

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
 15  New_Gender          55500 non-null  int64
dtypes: float64(1), int64(3), str(12)
memory usage: 15.1 MB

In [37]:
doctor_counts = doctor_counts.sort_values(by='Total_Patients_Treated', ascending=False)
df["doctor_count"] = doctor_counts["Total_Patients_Treated"]

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
 15  New_Gender          55500 non-null  int64
 16  doctor_count        39939 non-null  float64
dtypes: float64(2), int64(3), str(12)
memory usage: 15.6 MB

In [ ]:
mean_billing = df['doctor_count'].mean()
std_billing = df['doctor_count'].std()
df['Z_Score'] = (df['doctor_count'] - mean_billing) / std_billing
outliers = df[df['Z_Score'].abs() > 3]
print(f"Dataset Mean: {mean_billing}")
print(f"Dataset Standard Deviation: {std_billing}\n")
print(f"Found {len(outliers)} outliers using the Z-score method:")
print(outliers[['Name', 'Age', 'Billing Amount', 'Z_Score']])

KeyError: 'doctor_count'

In [ ]:
doctor_counts

                       Doctor Name  Total_Patients_Treated
27952  Michael Smith                                    28
18956  John Smith                                       23
32304  Robert Smith                                     22
10289  David Smith                                      21
27731  Michael Johnson                                  20
...                            ...                     ...
39934  Zoe Knight                                        1
39935  Zoe Nichols                                       1
39936  Zoe Roberts                                       1
6403   Carrie Thompson                                   1
39923  Zachary Whitaker                                  1

[39939 rows x 2 columns]

KeyError: 'doctor_count'

In [32]:
Q1 = df['doctor_count'].quantile(0.25)
Q3 = df['doctor_count'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['doctor_count'] < lower_bound) | (df['doctor_count'] > upper_bound)]
print(f"Lower Threshold Boundary: {lower_bound}")
print(f"Upper Threshold Boundary: {upper_bound}")
print("\nDetected Outliers in 'Billing Amount' column:")
print(len(outliers))

Lower Threshold Boundary: 1.0
Upper Threshold Boundary: 1.0

Detected Outliers in 'Billing Amount' column:
9765