In [1]:
pip i pandas

Note: you may need to restart the kernel to use updated packages.

ERROR: unknown command "i"

In [4]:
import pandas as pd
s = pd.Series([1,2,3,4],
              index=["SAhil" , "Raj","Ved"])
print(s)

ValueError: Length of values (4) does not match length of index (3)

In [ ]:
marks = pd.Series(

[80, 90, 70],

index=["John", "Mike", "Alice"]
)
print(marks)



print(s)

John     80
Mike     90
Alice    70
dtype: int64

In [7]:
import pandas as pd
s = pd.Series(
    [1,2,3],
    index=["SAhil" , "Raj","Ved"])

print(s)

SAhil    1
Raj      2
Ved      3
dtype: int64

In [8]:
s1= {
    "sahil":1,
    "Rahh":2,
    "Sai":3
}
marks = pd.Series(s1)
print(marks)

sahil    1
Rahh     2
Sai      3
dtype: int64

In [29]:
data = [
    ["John",25,50000],
    ["Mike",30,60000],
    ["Alice",28,70000],
    ["Sahil",18,1000000]
]

df = pd.DataFrame(
    data,
    columns=["Name","Age","Salary"]
)

print(df)
# df["Name"]
# df.iloc[0]
# df.head()
print(df.shape)
print(df.size)
df.columns
df.index
df.dtypes

    Name  Age   Salary
0   John   25    50000
1   Mike   30    60000
2  Alice   28    70000
3  Sahil   18  1000000
(4, 3)
12

Name        str
Age       int64
Salary    int64
dtype: object

In [ ]:
employees = pd.DataFrame({
    "Name":["John","Mike","Alice"],
    "Department":["IT","HR","Finance"],
    "Salary":[50000,60000,70000]
})

employees["Salary"].mean()
employees[employees["Department"]=="IT"]

   Name Department  Salary
0  John         IT   50000

In [68]:
import pandas as pd
df = pd.read_csv("employees.csv")
df.head(10)
df.fillna(0)
df.drop_duplicates()

df["Gender"]

0        Male
1        Male
2      Female
3        Male
4        Male
        ...
995       NaN
996      Male
997      Male
998      Male
999      Male
Name: Gender, Length: 1000, dtype: str

In [54]:
# df.iloc[0]
df.head(20)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product

In [73]:
df["Team"] = df["Team"].fillna("0")

In [74]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NA
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [75]:
print(df)

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                    NA
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]

In [76]:
df["Team"] = df["Team"].fillna("0")

In [78]:
print(df)

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                    NA
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]